"""Independent synthetic 13-episode preparation -> Node checks -> Python ledger.
No browser or remote draft is used. Observations are authored from explicit fixture
text/positions, not generated by renderPlan or by cloning expected canonical blocks.
"""
from __future__ import annotations
import copy
import hashlib
import json
from pathlib import Path
import subprocess
import sys
import tempfile
import unittest
from PIL import Image

IMPL=Path(__file__).resolve().parents[1]
sys.path.insert(0,str(IMPL/'skills/naver-series-workflow/scripts'))
import prepare_series as workflow
from execution_state import ExecutionKey,ExecutionStore

class SeriesSimulationTests(unittest.TestCase):
    def setUp(self):
        self.temp=tempfile.TemporaryDirectory(); self.root=Path(self.temp.name).resolve(); self.inputs=self.root/'inputs'; self.inputs.mkdir()
        self.manifest=self.inputs/'series.json'; entries=[]
        for ep in range(3,16):
            folder=self.inputs/f'episode-{ep:02d}'; folder.mkdir()
            for n in range(1,6): Image.new('RGB',(3,3),(ep,n,100)).save(folder/f'{n}.png')
            article=f'''# 실습 {ep}

첫 번째 문단입니다.

![첫 이미지](1.png)

## 단계 {ep}

두 번째 **강조** 문단입니다.

![둘 이미지](2.png)

세 번째 문단입니다.

![셋 이미지](3.png)

네 번째 문단입니다.

![넷 이미지](4.png)

**핵심 요약**

- 확인 하나
- 확인 둘

![다섯 이미지](5.png)

마지막 정리입니다.

**태그**

#연습 #시리즈
'''
            (folder/'article.md').write_text(article);(folder/'editorial.json').write_text('{"synthetic":true}')
            entries.append({'episode':ep,'article':str(folder/'article.md'),'editorial':str(folder/'editorial.json'),'review':str(folder/'review.json')})
        self.manifest.write_text(workflow.encoded({'schema':'naver-series/v1','series_id':'synthetic-13','target_blog':'fixture-blog','requested_episodes':list(range(3,16)),'requirements':{'images_per_episode':5,'tag_line_max_chars':100},'episodes':entries}))
        report=workflow.prepare(self.manifest,self.inputs,self.root/'prepared','synthetic',check=True)
        for entry in report['episodes']:
            review={'schema':'naver-review/v1','status':'passed','content_revision':entry['content_revision'],'checks':[{'id':name,'status':'passed','evidence':'Independently authored synthetic fixture; not review of any real article.'} for name in sorted(workflow.REVIEW_CHECKS)],'reviewed_by':'synthetic-test','reviewed_at':'2026-09-12T00:00:00+00:00'}
            (self.inputs/f"episode-{entry['episode']:02d}/review.json").write_text(workflow.encoded(review))
        self.prepared=workflow.prepare(self.manifest,self.inputs,self.root/'prepared','synthetic')
        self.run=self.root/'prepared/synthetic'; self.events=self.root/'events'
    def tearDown(self):self.temp.cleanup()
    def node(self,request):
        result=subprocess.run(['node',str(IMPL/'skills/naver-smarteditor-drafter/scripts/smarteditor_checks.mjs')],input=json.dumps(request),text=True,capture_output=True,check=True)
        return json.loads(result.stdout)
    def identity(self,ep):
        entry=self.prepared['episodes'][ep-3]
        return {'environment':'simulation','target_blog':'fixture-blog','content_revision':entry['content_revision']}
    def observation(self,ep,blank=False):
        def paragraph(text,marks=None):return {'kind':'paragraph','text':text,'marks':marks or []}
        def quote(text,style):return {'kind':'quotation','text':text,'style':style,'marks':[]}
        def image(n):return {'kind':'image','loaded':True,'asset_sha256':hashlib.sha256((self.inputs/f'episode-{ep:02d}/{n}.png').read_bytes()).hexdigest(),'asset_evidence_ref':f'simulation-uploaded-local-file-{ep}-{n}'}
        components=[] if blank else [paragraph('첫 번째 문단입니다.'),image(1),quote(f'단계 {ep}','quotation_bubble'),
            paragraph('두 번째 강조 문단입니다.',[{'type':'bold','start':5,'end':7}]),image(2),paragraph('세 번째 문단입니다.'),image(3),
            paragraph('네 번째 문단입니다.'),image(4),quote('핵심 요약','quotation_line'),paragraph('• 확인 하나'),paragraph('• 확인 둘'),image(5),paragraph('마지막 정리입니다.')]
        for i,c in enumerate(components):c['component_id']=f'actual-sim-component-{ep}-{i}'
        return {'schema':'smarteditor-observation/v1','environment':'simulation','target_blog':'fixture-blog','observed_at':'2026-09-12T00:00:00+00:00',
                'evidence_ref':f'simulation-observation-{ep}-'+('blank' if blank else 'content'),'coverage':'complete','body_root_observed':True,
                'title_fields':[{'component_id':f'actual-sim-title-{ep}','text':'' if blank else f'실습 {ep}'}],
                'components':components,'unsupported_components':[],'recovery_pending':False,'inflight_operations':[],
                'tags_observed':True,'tags':[] if blank else ['연습','시리즈'],
                'draft_identity':{'reference':f'simulation-server-draft-{ep}','matched_unique':True,'evidence_ref':f'simulation-server-record-{ep}'}}
    def verify(self,ep,scope,observation=None):
        identity=self.identity(ep)
        if scope in ('blank_verified','editor_checked'):
            return self.node({'command':'verify_blank','identity':identity,'observation':observation or self.observation(ep,True),'options':{'scope':scope}})
        post=json.loads((self.run/f'episode-{ep:02d}/naver-post.json').read_text());assets=json.loads((self.run/f'episode-{ep:02d}/asset-integrity.json').read_text())['assets']
        return self.node({'command':'verify_content','post':post,'assets':assets,'identity':identity,'observation':observation or self.observation(ep),'options':{'scope':scope,'draftRef':f'simulation-server-draft-{ep}'}})
    def effect(self,store,key,lease,name,observed):
        operation=store.begin_operation(key,lease,name)
        store.finish_operation(key,lease,operation,outcome='observed',observed=observed,evidence_ref='simulation-effect-'+operation)
    def test_thirteen_sequential_drafts_resume_lost_ack_without_duplicate(self):
        self.assertEqual(self.prepared['totals'],{'requested':13,'ready':13,'images':65,'missing':0})
        store=ExecutionStore(self.events,environment='simulation'); lease=store.acquire('fixture-blog','simulation'); saved_ids=[]
        for ep in range(3,16):
            info=workflow.status(self.run,execution_root=self.events,environment='simulation')
            self.assertEqual(info['next_episode'],ep); self.assertEqual(info['next_action'],'start')
            identity=self.identity(ep);key=ExecutionKey('fixture-blog','synthetic-13',ep,identity['content_revision'])
            store.start(key,lease);initial=self.verify(ep,'editor_checked');self.assertEqual(initial['status'],'passed')
            store.verify(key,lease,'editor_checked',initial)
            self.effect(store,key,lease,'insert_block',{'synthetic_body_inserted':True})
            for n in range(1,6):self.effect(store,key,lease,'upload_image',{'simulation_image':n,'loaded':True})
            input_evidence=self.verify(ep,'input_verified');self.assertEqual(input_evidence['status'],'passed',input_evidence['issues'])
            store.verify(key,lease,'input_verified',input_evidence)
            operation=store.begin_operation(key,lease,'save');saved_ids.append(f'simulation-server-draft-{ep}')
            reopened=self.verify(ep,'reopened_verified');self.assertEqual(reopened['status'],'passed')
            if ep==9:
                # Simulated remote save exists, but no result event survived. Fresh store cannot auto-retry.
                store.release(lease);store=ExecutionStore(self.events,environment='simulation')
                paused=workflow.status(self.run,execution_root=self.events,environment='simulation')
                self.assertEqual(paused['next_episode'],9);self.assertEqual(paused['next_action'],'reconcile_save');self.assertEqual(paused['queue'],[])
                lease=store.acquire('fixture-blog','resumed-simulation');store.reconcile_saved(key,lease,reopened)
                save={**identity,'save_acknowledged':False,'saved_reconciled':True,'evidence_ref':store.status(key)['last_event_hash'],'reconciliation_evidence_ref':reopened['evidence_ref']}
            else:
                store.finish_operation(key,lease,operation,outcome='observed',observed={'save_acknowledged':True},evidence_ref='simulation-ack')
                self.effect(store,key,lease,'open_saved',{'draft':saved_ids[-1]});store.verify(key,lease,'reopened_verified',reopened)
                save={**identity,'save_acknowledged':True,'evidence_ref':'simulation-ack'}
            before_blank=workflow.status(self.run,execution_root=self.events,environment='simulation')
            self.assertEqual(before_blank['next_action'],'verify_blank_only');self.assertEqual(before_blank['queue'],[])
            self.effect(store,key,lease,'new_editor',{'new_editor_opened':True})
            blank=self.verify(ep,'blank_verified');store.verify(key,lease,'blank_verified',blank)
            gate=self.node({'command':'can_advance','identity':identity,'input':input_evidence,'save':save,'reopened':reopened,'blank':blank})
            self.assertTrue(gate['allowed'],gate)
            count=store.status(key)['event_count'];store.start(key,lease);self.assertEqual(store.status(key)['event_count'],count)
        store.release(lease)
        final=workflow.status(self.run,execution_root=self.events,environment='simulation')
        self.assertTrue(final['execution_complete']);self.assertFalse(final['live_complete']);self.assertEqual(final['remaining_episodes'],[])
        self.assertEqual(len(saved_ids),13);self.assertEqual(len(set(saved_ids)),13)
        live=workflow.status(self.run,execution_root=self.events,environment='live')
        self.assertEqual(live['integrity'],'failed');self.assertFalse(live['live_complete'])
    def test_wrong_middle_image_stops_at_input_and_preserves_unknown(self):
        obs=self.observation(3);obs['components'][6],obs['components'][8]=obs['components'][8],obs['components'][6]
        bad=self.verify(3,'input_verified',obs);self.assertEqual(bad['status'],'failed')
        self.assertFalse(bad['checks']['image_order'])
        obs=self.observation(3);obs['tags_observed']=False;obs['tags']=None
        missing=self.verify(3,'input_verified',obs);self.assertEqual(missing['status'],'unknown');self.assertIsNone(missing['observed']['tags'])
        self.assertFalse(self.node({'command':'can_advance','identity':self.identity(3),'input':missing,'save':None,'reopened':None,'blank':None})['allowed'])

if __name__=='__main__':unittest.main()
